#!/bin/bash
IMAGE=ibmcom/swift-ubuntu:3.1.1
CONTAINER=swift-test
docker rm $CONTAINER 
docker run -it --privileged --rm --name $CONTAINER -v "$PWD":/project $IMAGE /bin/bash -c 'cd /project; swift test'
